# Generated by Django 5.2.11 on 2026-03-01 17:00

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('self_drop', 'Self Drop-off'), ('pickup', 'Schedule Pickup')], max_length=20)),
                ('clothing_type', models.CharField(help_text='e.g. T-Shirt, Jeans, Jacket', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(help_text='e.g. Good, Fair, Needs Repair', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Any extra details about the clothes')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('coins_earned', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('received', 'Received at Center'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
